// This file will be generated by GraphQL Codegen
// Run: npm run codegen
// 
// Placeholder export to prevent TypeScript errors before codegen runs
export const graphql = (query: TemplateStringsArray | string): any => {
  throw new Error('GraphQL Codegen has not been run. Please run: npm run codegen');
};

